import Product from "../models/productSchema.js";
import asyncHandler from "../utils/asyncHandler.js";
import Category from '../models/categorySchema.js'

export const getProducts = asyncHandler(async (req, res) => {
    let {
        page = 1,
        limit = 10,
        search,
        category,
        minPrice,
        maxPrice,
        brand,
        rating,
        sort
    } = req.query;

    page = Number(page);
    limit = Number(limit);

    const query = {};

    // TEXT SEARCH (text index)
    if (search) {
        query.$text = { $search: search };
    }

    // BASIC FILTERS
    if (category) query.category = category;
    if (brand) query.brand = brand;

    if (rating && !isNaN(rating)) {
        query.rating = { $gte: Number(rating) };
    }

    // PRICE RANGE FILTER
    if (minPrice || maxPrice) {
        query.$and = [];

        if (minPrice && !isNaN(minPrice)) {
            query.$and.push({ maxPrice: { $gte: Number(minPrice) } });
        }

        if (maxPrice && !isNaN(maxPrice)) {
            query.$and.push({ minPrice: { $lte: Number(maxPrice) } });
        }
    }

    // SORTING
    let sortOption = {};

    switch (sort) {
        case "price_asc":
            sortOption.minPrice = 1;
            break;
        case "price_desc":
            sortOption.minPrice = -1;
            break;
        case "newest":
            sortOption.createdAt = -1;
            break;
        case "rating":
            sortOption.rating = -1;
            break;
        default:
            sortOption.createdAt = -1;
    }

    const products = await Product.find(query)
        .populate("category", "name")
        .sort(sortOption)
        .skip((page - 1) * limit)
        .limit(limit)
        .lean(); //for js object and faster fetch

    const total = await Product.countDocuments(query);

    res.json({
        success: true,
        data: {
            products,
            pagination: {
                total,
                page,
                pages: Math.ceil(total / limit)
            }
        }
    });
});

//get product by id
export const getProductById = asyncHandler(async (req, res) => {
    const { id } = req.params;
    const product = await Product.findById(id).populate("category", "name");

    if (!product) {
        return res.status(404).json({
            success: false,
            message: "product not found"
        })
    }

    res.status(200).json({
        success: true,
        product
    })
})

//create/add product
export const addProduct = asyncHandler(async (req, res) => {
    // Destructure required data from request body
    const {
        title,
        description,
        brand,
        category,
        attributes,
        variants,
    } = req.body;

    // Validate required fields
    if (!title || !description || !category || !variants?.length) {
        return res.status(400).json({
            success: false,
            message: "Missing required fields"
        });
    }

    // Validate at least one variant exists
    if (!variants || variants.length === 0) {
        return res.status(400).json({
            success: false,
            message: "At least one variant is required"
        });
    }

    // Process each variant and calculate prices
    const processedVariants = variants.map((variant, index) => {
        // Validate price exists and is greater than 0
        if (!variant.price || variant.price <= 0) {
            throw new Error(`Variant ${index}: Price must be a positive number`);
        }

        // Validate discount price if provided
        if (variant.discountPrice && variant.discountPrice >= variant.price) {
            throw new Error(`Variant ${index}: Discount price must be less than original price`);
        }

        // Auto-generate SKU from product title and variant attributes
        // Example: "iPhone 14" + "256GB" + "Black" = "iPhone14-256GB-Black"
        const baseSku = title.replace(/\s+/g, '').toLowerCase();
        const attributeSku = Object.values(variant.attributes || {})
            .filter(Boolean)
            .map(attr => String(attr).replace(/\s+/g, ''))
            .join('-')
            .toLowerCase();

        const autoGeneratedSku = attributeSku ? `${baseSku}-${attributeSku}` : baseSku;

        return {
            attributes: variant.attributes,
            price: variant.price,
            discountPrice: variant.discountPrice || null,
            stock: variant.stock,
            sku: autoGeneratedSku,
            // images: variant.images || []
        };
    });

    // Extract all prices from processed variants
    const prices = processedVariants.map(v => v.discountPrice || v.price);

    // Calculate minimum and maximum prices
    const minPrice = Math.min(...prices);
    const maxPrice = Math.max(...prices);

    // Create product in database
    const product = await Product.create({
        title,
        description,
        brand,
        category,
        attributes,
        variants: processedVariants,
        minPrice,
        maxPrice,
    });

    // Return success response with created product
    res.status(201).json({
        success: true,
        message: "Product created successfully",
        data: product,
    });
});

//update product
export const updateProduct = asyncHandler(async (req, res) => {
    const { id } = req.params;

    const {
        title,
        description,
        brand,
        category,
        attributes,
        variants
    } = req.body;

    //find product
    const product = await Product.findById(id);

    if (!product) {
        return res.status(404).json({
            success: false,
            message: "Product not found"
        });
    }

    //update basic fields(only if provided)
    if (title) product.title = title;
    if (description) product.description = description;
    if (brand) product.brand = brand;
    if (category) product.category = category;
    if (attributes) product.attributes = attributes;

    // if variants updated → recalc prices
    if (variants && variants.length > 0) {

        // validate variants
        for (const v of variants) {
            if (!v.price) {
                return res.status(400).json({
                    success: false,
                    message: "Each variant must have price"
                });
            }
        }

        product.variants = variants;

        const prices = variants.map(v => v.discountPrice || v.price);

        product.minPrice = Math.min(...prices);
        product.maxPrice = Math.max(...prices);
    }

    await product.save();

    res.status(200).json({
        success: true,
        data: product
    });
});

//delete product
export const deleteProduct = asyncHandler(async (req, res) => {
    const { id } = req.params;

    const product = await Product.findByIdAndDelete(id);

    if (!product) {
        return res.status(404).json({
            success: false,
            message: "Product not found"
        });
    }

    res.status(200).json({
        success: true,
        message: "Product deleted successfully"
    });
});

//create category product using category model
export const addCategory = asyncHandler(async (req, res) => {
    const { name, parent } = req.body;

    // Basic validation
    if (!name) {
        return res.status(400).json({
            success: false,
            message: "Category name is required"
        });
    }

    const normalizedName = name.trim().toLowerCase();

    // Check duplicate
    const existing = await Category.findOne({ name: normalizedName });
    if (existing) {
        return res.status(400).json({
            success: false,
            message: "Category already exists"
        });
    }

    // Validate parent (if provided)
    let parentCategory = null;

    if (parent) {
        if (!mongoose.Types.ObjectId.isValid(parent)) {
            return res.status(400).json({
                success: false,
                message: "Invalid parent category ID"
            });
        }

        parentCategory = await Category.findById(parent);

        if (!parentCategory) {
            return res.status(404).json({
                success: false,
                message: "Parent category not found"
            });
        }
    }

    const category = await Category.create({
        name: normalizedName,
        parent: parentCategory ? parentCategory._id : null
    });

    res.status(201).json({
        success: true,
        data: category
    });

});